

using Api;
using DataAccess;
using DataAccess.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

ConfigureServices(builder.Services, builder.Configuration);

var app = builder.Build();

Configure(app);

app.Run();

public partial class Program
{
    public static void ConfigureServices(IServiceCollection services, IConfiguration configuration)
    {
        var connectionString = configuration.GetConnectionString("DbConnectionString");
        services.AddDbContext<MyDbContext>(conf => conf.UseNpgsql(connectionString));
        //TODO add services to scope eventually

        services.AddIdentity<ApplicationUser, IdentityRole<Guid>>(options =>
        {
            //TODO Tweak later - just autogenerated for now
            options.Password.RequireDigit = false;
            options.Password.RequireLowercase = false;
            options.Password.RequireNonAlphanumeric = false;
            options.Password.RequireUppercase = false;
            options.Password.RequiredLength = 6;
        })
            .AddEntityFrameworkStores<MyDbContext>()
            .AddDefaultTokenProviders();

        //TODO swap to JWT
        services.AddAuthentication(options =>
        {
            options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
            options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
        }).AddCookie(IdentityConstants.ApplicationScheme);
        
        services.AddAuthorization();

        services.AddControllers();
        services.AddProblemDetails();
        services.AddExceptionHandler<ExceptionHandler>();
        services.AddCors();
    }

    public static void Configure(WebApplication app)
    {
        app.UseExceptionHandler();
        //TODO switch to with origins for prod (or split to dev vs prod and use both)
        app.UseCors(conf => conf.
            AllowAnyHeader().
            AllowAnyMethod().
            AllowAnyOrigin()
            .SetIsOriginAllowed(x=> true));

        if (app.Environment.IsDevelopment())
        {
            app.UseOpenApi();
            app.UseSwaggerUi();
            //TODO add TS Api client generation here
        }
        app.UseAuthentication();
        app.UseAuthorization();
        
        app.MapControllers();
    }
}
