

using System.Security.Claims;
using System.Text;
using api;
using Api;
using Api.Security;
using Api.Services;
using Api.Services.Email;
using Api.Services.Interfaces;
using DataAccess;
using DataAccess.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);

ConfigureServices(builder.Services, builder.Configuration);

var app = builder.Build();

await SeedIdentityAsync(app);

Configure(app);

app.Run();

public partial class Program
{
    public static void ConfigureServices(IServiceCollection services, IConfiguration configuration)
    {
        var connectionString = configuration.GetConnectionString("DbConnectionString");
        services.AddDbContext<MyDbContext>(conf => conf
            .UseNpgsql(connectionString,
                b => b.MigrationsAssembly("DataAccess")));
        
        services.Configure<SmtpOptions>(configuration.GetSection("Smtp"));
        
        services.AddScoped<ITokenService, TokenService>();
        services.AddScoped<IAuthService, AuthService>();
        services.AddScoped<IPlayerService, PlayerService>();
        services.AddScoped<IBoardService, BoardService>();
        services.AddScoped<IGameService, GameService>();
        services.AddScoped<IBoardSubscriptionService, BoardSubscriptionService>();
        services.AddScoped<ITransactionService, TransactionService>();
        services.AddScoped<IEmailSender, SmtpEmailSender>();
        
        services.AddIdentity<ApplicationUser, IdentityRole<Guid>>(options =>
        {
            //TODO Tweak later - just autogenerated for now
            options.Password.RequireDigit = false;
            options.Password.RequireLowercase = false;
            options.Password.RequireNonAlphanumeric = false;
            options.Password.RequireUppercase = false;
            options.Password.RequiredLength = 6;
            //TODO maybe change to true to enforce the activation link harder
            options.SignIn.RequireConfirmedEmail = false;
        })
            .AddEntityFrameworkStores<MyDbContext>()
            .AddDefaultTokenProviders();
        
        var jwtSettings = configuration.GetSection("Jwt");
        var key = Encoding.UTF8.GetBytes(jwtSettings["Key"]!);

        services.AddAuthentication(options =>
        {
            options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
        }).AddJwtBearer(options =>
        {
            options.SaveToken = true;
            options.RequireHttpsMetadata = false;
            options.TokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidateAudience = true,
                ValidateLifetime = true,
                ValidateIssuerSigningKey = true,
                ValidIssuer = jwtSettings["Issuer"]!,
                ValidAudience = jwtSettings["Audience"]!,
                IssuerSigningKey = new SymmetricSecurityKey(key),
                ClockSkew = TimeSpan.Zero,
                NameClaimType = ClaimTypes.NameIdentifier,
                RoleClaimType = ClaimTypes.Role
            };
        });
        
        services.AddAuthorizationBuilder()
                    .AddPolicy("ActivePlayer", policy =>
                policy.RequireClaim("isActivePlayer", "true"));
        
        services.AddControllers();
        services.AddOpenApiDocument();
        services.AddProblemDetails();
        services.AddExceptionHandler<ExceptionHandler>();
        services.AddCors(options =>
        {
            options.AddPolicy("Frontend", p => p
                .WithOrigins("http://localhost:5173")
                .AllowAnyMethod()
                .AllowAnyHeader());
        });
    }
    
    public static void Configure(WebApplication app)
    {
        app.UseExceptionHandler();
        
        app.UseRouting();
        
        //app.UseCors(p => p.WithOrigins(UrlConstants.FrontEndUrl).AllowAnyHeader().AllowAnyMethod());
        
        app.UseCors("Frontend");
        
        if (app.Environment.IsDevelopment())
        {
            app.UseOpenApi();
            app.UseSwaggerUi();
            app.GenerateApiClientsFromOpenApi("/../../client/src/generated-ts-client.ts").GetAwaiter().GetResult();
            
        }
        app.UseAuthentication();
        app.UseAuthorization();
        
        app.MapControllers();
    }

    public static async Task SeedIdentityAsync(WebApplication app)
    {
        using var scope = app.Services
            .CreateScope();
        var roleManager = scope.ServiceProvider
            .GetRequiredService<RoleManager<IdentityRole<Guid>>>();
        
        var userManager = scope.ServiceProvider
            .GetRequiredService<UserManager<ApplicationUser>>();
        
        string[] roleNames = { "Admin", "Player" };

        foreach (var roleName in roleNames)
        {
            if (!await roleManager
                    .RoleExistsAsync(roleName))
            {
                await roleManager
                    .CreateAsync(new IdentityRole<Guid>(roleName));
            }
        }
        const string adminEmail = "admin@admin.dk";
        var adminUser = await userManager
            .FindByEmailAsync(adminEmail);

        
        SeedOneUserAsync(userManager).Wait();
        if (adminUser == null)
        {
            adminUser = new ApplicationUser
            {
                UserName = adminEmail,
                FullName = "Admin", 
                Email = adminEmail,  
                EmailConfirmed = true
            };

            //TODO change password before deploying
            var result = await userManager.CreateAsync(adminUser, "123456");

            if (result.Succeeded)
            {
                await userManager.AddToRoleAsync(adminUser, "Admin");
            }
            //TODO log/throw something here
            
        }
    }
    
    //TODO remove
    private static async Task SeedOneUserAsync(UserManager<ApplicationUser> userManager)
    {
        const string userEmail = "active@test.dk";
        var user = await userManager
            .FindByEmailAsync(userEmail);

        if (user == null)
        {
            user = new ApplicationUser
            {
                UserName = userEmail,
                FullName = "ActiveTestUser", 
                Email = userEmail,  
                EmailConfirmed = true,
                IsActivePlayer = true,
            };

            //TODO change password before deploying
            var result = await userManager.CreateAsync(user, "123456");

            if (result.Succeeded)
            {
                await userManager.AddToRoleAsync(user, "Player");
            }
            //TODO log/throw something here
        }
        
    }
}
